"""Add password_hash column and indexes

Revision ID: f2977553ac62
Revises: 
Create Date: 2024-12-20 18:01:17.915878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2977553ac62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suyan_period')
    with op.batch_alter_table('taobao_account', schema=None) as batch_op:
        batch_op.drop_index('dffdd')
        batch_op.drop_index('ssffd')
        batch_op.drop_index('taobao_account_index', mysql_length={'tbid': 191})

    op.drop_table('taobao_account')
    with op.batch_alter_table('dx_phonelogo', schema=None) as batch_op:
        batch_op.drop_index('ded')
        batch_op.drop_index('dfedds')
        batch_op.drop_index('fdfdees')
        batch_op.drop_index('feed')
        batch_op.drop_index('fgdd')

    op.drop_table('dx_phonelogo')
    op.drop_table('kaolazongnomy')
    with op.batch_alter_table('taobao_account_tb', schema=None) as batch_op:
        batch_op.drop_index('dffdd')
        batch_op.drop_index('ssffd')
        batch_op.drop_index('taobao_account_index', mysql_length={'tbid': 191})

    op.drop_table('taobao_account_tb')
    op.drop_table('taozi_financial')
    op.drop_table('taobao_account_remarks')
    op.drop_table('yin_jkd')
    with op.batch_alter_table('qq_qunuse', schema=None) as batch_op:
        batch_op.drop_index('fdd')

    op.drop_table('qq_qunuse')
    with op.batch_alter_table('douyintianmao', schema=None) as batch_op:
        batch_op.drop_index('cffd')
        batch_op.drop_index('dvdc')

    op.drop_table('douyintianmao')
    with op.batch_alter_table('dx_konghao', schema=None) as batch_op:
        batch_op.drop_index('idx_odk')
        batch_op.drop_index('idx_phon')

    op.drop_table('dx_konghao')
    with op.batch_alter_table('anhui_user', schema=None) as batch_op:
        batch_op.drop_index('dfd')
        batch_op.drop_index('dfe')
        batch_op.drop_index('dfrfc')
        batch_op.drop_index('dvvc')
        batch_op.drop_index('fgrr')
        batch_op.drop_index('idss')

    op.drop_table('anhui_user')
    with op.batch_alter_table('hedanzhuan', schema=None) as batch_op:
        batch_op.drop_index('idx_id1')
        batch_op.drop_index('idx_id2')

    op.drop_table('hedanzhuan')
    with op.batch_alter_table('kao_token', schema=None) as batch_op:
        batch_op.drop_index('id_token')

    op.drop_table('kao_token')
    op.drop_table('kd_cha')
    with op.batch_alter_table('ali_ua', schema=None) as batch_op:
        batch_op.drop_index('ddd')

    op.drop_table('ali_ua')
    with op.batch_alter_table('jingheng', schema=None) as batch_op:
        batch_op.drop_index('dds')
        batch_op.drop_index('id_ce1')

    op.drop_table('jingheng')
    op.drop_table('suyan_login')
    with op.batch_alter_table('yunjiao_token', schema=None) as batch_op:
        batch_op.drop_index('dee')
        batch_op.drop_index('sdfdf')

    op.drop_table('yunjiao_token')
    op.drop_table('user_price')
    with op.batch_alter_table('langzidx', schema=None) as batch_op:
        batch_op.drop_index('dcsss')
        batch_op.drop_index('ddss')
        batch_op.drop_index('dfss')
        batch_op.drop_index('dressw')
        batch_op.drop_index('gfdfd')
        batch_op.drop_index('rfdds')

    op.drop_table('langzidx')
    with op.batch_alter_table('kaolashuju02', schema=None) as batch_op:
        batch_op.drop_index('cookie_index', mysql_length={'Cookie': 255})
        batch_op.drop_index('dddf', mysql_length={'ys_sess': 255})
        batch_op.drop_index('defw')
        batch_op.drop_index('dsffs', mysql_length={'ys_sess': 255})
        batch_op.drop_index('ffedd')
        batch_op.drop_index('gtrf')
        batch_op.drop_index('idx_account1_shijian')
        batch_op.drop_index('idx_account1_shijianwd')
        batch_op.drop_index('idx_account1_shijianwdww')
        batch_op.drop_index('idx_orid1')
        batch_op.drop_index('idx_orid3')
        batch_op.drop_index('idx_shdw')
        batch_op.drop_index('idx_shijian')
        batch_op.drop_index('idx_shoujihaoma')
        batch_op.drop_index('idx_state1_alitype_shijian')
        batch_op.drop_index('jhhnnn')
        batch_op.drop_index('llkk')
        batch_op.drop_index('sdddssx')
        batch_op.drop_index('shoujihaoma_index')
        batch_op.drop_index('tdfsss')

    op.drop_table('kaolashuju02')
    with op.batch_alter_table('rmw_token', schema=None) as batch_op:
        batch_op.drop_index('cha_dx')
        batch_op.drop_index('cishu_index')
        batch_op.drop_index('ddd')
        batch_op.drop_index('ddrr')
        batch_op.drop_index('ddss')
        batch_op.drop_index('fdggfdg')
        batch_op.drop_index('fdgr')
        batch_op.drop_index('ffdd')
        batch_op.drop_index('gfd')
        batch_op.drop_index('gfhfd')
        batch_op.drop_index('ghgf')
        batch_op.drop_index('id')
        batch_op.drop_index('idd')
        batch_op.drop_index('jiange_index')
        batch_op.drop_index('setss_index')
        batch_op.drop_index('utined')

    op.drop_table('rmw_token')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('rmw_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userid', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('cishu', mysql.VARCHAR(length=5), server_default=sa.text("'5'"), nullable=True),
    sa.Column('setss', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=True, comment='0=启用  1=禁用 2=重新登陆'),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('msg', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('shijian', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('jiange', mysql.VARCHAR(length=2), server_default=sa.text("'8'"), nullable=True),
    sa.Column('xufeishijian', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('mmm', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('IPaddress', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Deviceid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('androidId', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('models', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True, comment='地区'),
    sa.Column('mssg', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('control', mysql.VARCHAR(length=2), server_default=sa.text("'0'"), nullable=True, comment='风控解除  0=未完成  1=完成'),
    sa.Column('pccooki', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('provinceCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cityCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nomy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('zonge', mysql.INTEGER(display_width=3), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'token'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rmw_token', schema=None) as batch_op:
        batch_op.create_index('utined', ['shijian', 'region'], unique=False)
        batch_op.create_index('setss_index', ['setss'], unique=False)
        batch_op.create_index('jiange_index', ['jiange'], unique=False)
        batch_op.create_index('idd', ['id'], unique=False)
        batch_op.create_index('id', ['phone'], unique=True)
        batch_op.create_index('ghgf', ['setss', 'shijian'], unique=False)
        batch_op.create_index('gfhfd', ['shijian', 'region'], unique=False)
        batch_op.create_index('gfd', ['cishu', 'setss'], unique=False)
        batch_op.create_index('ffdd', ['setss', 'msg'], unique=False)
        batch_op.create_index('fdgr', ['zonge'], unique=False)
        batch_op.create_index('fdggfdg', ['phone'], unique=False)
        batch_op.create_index('ddss', ['xufeishijian'], unique=False)
        batch_op.create_index('ddrr', ['nomy'], unique=False)
        batch_op.create_index('ddd', ['setss'], unique=False)
        batch_op.create_index('cishu_index', ['cishu'], unique=False)
        batch_op.create_index('cha_dx', ['userid'], unique=False)

    op.create_table('kaolashuju02',
    sa.Column('id', mysql.INTEGER(display_width=110), autoincrement=True, nullable=False),
    sa.Column('shoujihaoma', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('paynomy', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nomy', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('payshang', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('orid1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('account1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pass', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shijian', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tafangorid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ys_sess', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('zhifu', mysql.VARCHAR(length=100), server_default=sa.text("'0'"), nullable=True),
    sa.Column('alipayacc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('taoorid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('alitype', mysql.VARCHAR(length=255), nullable=True, comment='1=考拉自主走单，2其他'),
    sa.Column('callback', mysql.VARCHAR(length=255), nullable=True, comment='回调地址'),
    sa.Column('guouserid', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('guokey', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('deltesta', mysql.VARCHAR(length=1), server_default=sa.text("'0'"), nullable=True, comment='0=未删除  1=已删除  2=已清空'),
    sa.Column('Cookie', mysql.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('kaolashuju02', schema=None) as batch_op:
        batch_op.create_index('tdfsss', ['tafangorid'], unique=False)
        batch_op.create_index('shoujihaoma_index', ['shoujihaoma'], unique=False)
        batch_op.create_index('sdddssx', ['orid1'], unique=False)
        batch_op.create_index('llkk', ['state1', 'shijian', 'alipayacc'], unique=False)
        batch_op.create_index('jhhnnn', ['state1', 'alitype'], unique=False)
        batch_op.create_index('idx_state1_alitype_shijian', ['state1', 'alitype', 'shijian'], unique=False)
        batch_op.create_index('idx_shoujihaoma', ['shoujihaoma'], unique=False)
        batch_op.create_index('idx_shijian', ['shijian'], unique=False)
        batch_op.create_index('idx_shdw', ['taoorid'], unique=False)
        batch_op.create_index('idx_orid3', ['payshang'], unique=False)
        batch_op.create_index('idx_orid1', ['orid1'], unique=True)
        batch_op.create_index('idx_account1_shijianwdww', ['zhifu', 'shijian', 'alitype', 'payshang'], unique=False)
        batch_op.create_index('idx_account1_shijianwd', ['alipayacc', 'alitype'], unique=False)
        batch_op.create_index('idx_account1_shijian', ['account1', 'shijian'], unique=False)
        batch_op.create_index('gtrf', ['shoujihaoma', 'shijian', 'alitype'], unique=False)
        batch_op.create_index('ffedd', ['deltesta'], unique=False)
        batch_op.create_index('dsffs', ['shoujihaoma', 'shijian', 'state1', 'ys_sess'], unique=False, mysql_length={'ys_sess': 255})
        batch_op.create_index('defw', ['callback'], unique=False)
        batch_op.create_index('dddf', ['state1', 'ys_sess', 'payshang'], unique=False, mysql_length={'ys_sess': 255})
        batch_op.create_index('cookie_index', ['Cookie'], unique=False, mysql_length={'Cookie': 255})

    op.create_table('langzidx',
    sa.Column('id', mysql.INTEGER(display_width=20), autoincrement=True, nullable=False),
    sa.Column('orderid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amount', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('payString', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('shijian', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='1=初始化  2=处理中  3=成功  4=超时'),
    sa.Column('systemorderid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('callback', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('langzidx', schema=None) as batch_op:
        batch_op.create_index('rfdds', ['systemorderid'], unique=False)
        batch_op.create_index('gfdfd', ['shijian', 'state'], unique=False)
        batch_op.create_index('dressw', ['shijian'], unique=False)
        batch_op.create_index('dfss', ['orderid'], unique=True)
        batch_op.create_index('ddss', ['phone'], unique=False)
        batch_op.create_index('dcsss', ['state'], unique=False)

    op.create_table('user_price',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('mianprice', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('yunjiao_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('cookie', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('sstuta', mysql.INTEGER(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='1=可用 2=不可用 12=其他设备登陆  13=超限'),
    sa.Column('cishu', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('shijian', mysql.DATETIME(), nullable=True),
    sa.Column('deveid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('token', mysql.VARCHAR(length=8000), nullable=True),
    sa.Column('ua', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('shdfp', mysql.VARCHAR(length=3100), nullable=True),
    sa.Column('linuxshi', mysql.DATETIME(), nullable=True),
    sa.Column('dfpd', mysql.VARCHAR(length=2300), nullable=True),
    sa.Column('osyip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('query', mysql.INTEGER(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment=' 0=初始化 1=已被获取'),
    sa.Column('lfikgjr', mysql.INTEGER(display_width=3), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('yunjiao_token', schema=None) as batch_op:
        batch_op.create_index('sdfdf', ['phone'], unique=True)
        batch_op.create_index('dee', ['sstuta', 'cishu'], unique=False)

    op.create_table('suyan_login',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('caretime', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('nomy', mysql.VARCHAR(length=255), nullable=True, comment='计费金额'),
    sa.Column('shichang', mysql.VARCHAR(length=255), nullable=True, comment='计费分钟'),
    sa.Column('leixing', mysql.VARCHAR(length=255), nullable=True, comment='1=上班和下班 2=奖励和处罚  3=记录警告'),
    sa.Column('msg', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=1), nullable=True, comment='2=客服  1=技术 3=财务'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('jingheng',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shopid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('userkey', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jingheng', schema=None) as batch_op:
        batch_op.create_index('id_ce1', ['orid'], unique=False)
        batch_op.create_index('dds', ['orid'], unique=True)

    op.create_table('ali_ua',
    sa.Column('userid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cookie', mysql.VARCHAR(length=5000), server_default=sa.text("'0'"), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cookie2', mysql.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ali_ua', schema=None) as batch_op:
        batch_op.create_index('ddd', ['userid'], unique=True)

    op.create_table('kd_cha',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('balance', mysql.DECIMAL(precision=65, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('kao_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('kao_token', schema=None) as batch_op:
        batch_op.create_index('id_token', ['token'], unique=True)

    op.create_table('hedanzhuan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orders', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('account', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('chongzhi', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('gonghuoshang', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shijian', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beilog', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shanghuorid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('setaa', mysql.VARCHAR(length=1), server_default=sa.text("'0'"), nullable=True, comment='0=正在处理中  1=已完结'),
    sa.Column('shangpin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dingshijian', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hedanzhuan', schema=None) as batch_op:
        batch_op.create_index('idx_id2', ['orders', 'account', 'shijian', 'setaa'], unique=False)
        batch_op.create_index('idx_id1', ['orders'], unique=True)

    op.create_table('anhui_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cishu', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('usxk', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('satue', mysql.INTEGER(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='0=正常 1=禁用'),
    sa.Column('qushij', mysql.DATETIME(), nullable=True),
    sa.Column('linshick', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shijian', mysql.DATETIME(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('anhui_user', schema=None) as batch_op:
        batch_op.create_index('idss', ['cishu', 'satue'], unique=False)
        batch_op.create_index('fgrr', ['satue', 'shijian'], unique=False)
        batch_op.create_index('dvvc', ['phone'], unique=False)
        batch_op.create_index('dfrfc', ['satue'], unique=False)
        batch_op.create_index('dfe', ['phone'], unique=True)
        batch_op.create_index('dfd', ['cishu'], unique=False)

    op.create_table('dx_konghao',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('statu', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True, comment='1=正常号码，4=空号'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dx_konghao', schema=None) as batch_op:
        batch_op.create_index('idx_phon', ['phone'], unique=False)
        batch_op.create_index('idx_odk', ['phone'], unique=True)

    op.create_table('douyintianmao',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('itemId', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount', mysql.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('douyintianmao', schema=None) as batch_op:
        batch_op.create_index('dvdc', ['amount'], unique=False)
        batch_op.create_index('cffd', ['itemId'], unique=True)

    op.create_table('qq_qunuse',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('qun', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('nomy', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('setaa', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True, comment='0=禁用 1=启动'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('qq_qunuse', schema=None) as batch_op:
        batch_op.create_index('fdd', ['qun'], unique=False)

    op.create_table('yin_jkd',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('picenomy', mysql.DECIMAL(precision=50, scale=3), nullable=True, comment='加款金额'),
    sa.Column('shijian', mysql.DATETIME(), nullable=True),
    sa.Column('msg', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('pice', mysql.DECIMAL(precision=50, scale=2), nullable=True, comment='面值金额'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('taobao_account_remarks',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tbid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('taozi_financial',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('statime', mysql.DATETIME(), nullable=True),
    sa.Column('lonamy', mysql.DECIMAL(precision=50, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('taobao_account_tb',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tbid', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('ck', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('cishu', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='0=无效   1=有效  2=cookie失效  3=黑名单 5=已使用'),
    sa.Column('read', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='0=未读   1=已读'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('taobao_account_tb', schema=None) as batch_op:
        batch_op.create_index('taobao_account_index', ['tbid', 'cishu', 'start_time', 'status', 'read'], unique=False, mysql_length={'tbid': 191})
        batch_op.create_index('ssffd', ['status'], unique=False)
        batch_op.create_index('dffdd', ['status', 'cishu'], unique=False)

    op.create_table('kaolazongnomy',
    sa.Column('zongnomy', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('dx_phonelogo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('shijian', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('provinces', mysql.VARCHAR(length=20), nullable=True, comment='省份'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dx_phonelogo', schema=None) as batch_op:
        batch_op.create_index('fgdd', ['phone'], unique=False)
        batch_op.create_index('feed', ['shijian'], unique=False)
        batch_op.create_index('fdfdees', ['provinces'], unique=False)
        batch_op.create_index('dfedds', ['shijian', 'name'], unique=False)
        batch_op.create_index('ded', ['name'], unique=False)

    op.create_table('taobao_account',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tbid', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('ck', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('cishu', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='0=无效   1=有效'),
    sa.Column('read', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='0=未读   1=已读'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('taobao_account', schema=None) as batch_op:
        batch_op.create_index('taobao_account_index', ['tbid', 'cishu', 'start_time', 'status', 'read'], unique=False, mysql_length={'tbid': 191})
        batch_op.create_index('ssffd', ['status'], unique=False)
        batch_op.create_index('dffdd', ['status', 'cishu'], unique=False)

    op.create_table('suyan_period',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('b_billing', mysql.VARCHAR(length=255), server_default=sa.text("'0'"), nullable=True, comment='白天计费价格'),
    sa.Column('member', mysql.VARCHAR(length=255), nullable=True, comment='会员级别'),
    sa.Column('bkai_Period', mysql.VARCHAR(length=255), nullable=True, comment='白天开始时间'),
    sa.Column('bjie_Period', mysql.VARCHAR(length=255), nullable=True, comment='白天结束时间'),
    sa.Column('t_billing', mysql.VARCHAR(length=255), nullable=True, comment='晚上通宵计费价格'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
